language: node_js
node_js:
  - "0.12"
before_script:
  - 'npm install -g bower'
  - 'bower install'
  - 'gem update --system'
  - 'gem install compass'
deploy:
  provider: heroku
  api_key:
    secure: "fa355fa8-ed14-44d1-b8e1-93a9936d9727"
